// Generated by CoffeeScript 1.7.1
(function() {
  var Q, capabilities, capabilityString, disableScreenshots, fs, getPath, matchScreenshot, matchesCapabilities, mkdirp, resemble, rimraf, saveFailureImages, screenshotBase, screenshotSizes, slug, takeScreenshot, _;

  fs = require('fs');

  mkdirp = require('mkdirp');

  rimraf = require('rimraf');

  slug = require('slug');

  resemble = require('resemble').resemble;

  Q = require('q');

  _ = require('lodash');

  capabilityString = '';

  capabilities = null;

  browser.getCapabilities().then(function(returnValue) {
    var browserName, platform, version;
    capabilities = returnValue.caps_;
    browserName = returnValue.caps_.browserName.toLowerCase();
    platform = returnValue.caps_.platform.toLowerCase();
    version = returnValue.caps_.version.toLowerCase();
    return capabilityString = "" + platform + "-" + browserName + "-" + version;
  });

  disableScreenshots = browser.params['disableScreenshots'];

  screenshotBase = browser.params['screenshotsBasePath'] || '.';

  screenshotSizes = browser.params['screenshotSizes'];

  matchesCapabilities = function(other) {
    var excludeKeys;
    excludeKeys = ['sizes'];
    return _.every(other, function(value, key) {
      if (excludeKeys.indexOf(key) !== -1) {
        return true;
      }
      return capabilities[key] === value;
    });
  };

  getPath = function(suite) {
    var buildName;
    buildName = function(suite) {
      var prefix;
      prefix = '';
      if (suite.parentSuite) {
        prefix = "" + (buildName(suite.parentSuite)) + " ";
      }
      return "" + prefix + suite.description;
    };
    return "" + screenshotBase + "/" + (slug(buildName(suite))) + "/" + (slug(capabilityString));
  };

  matchScreenshot = function(spec, screenshotName, screenshot) {
    var filename, label, path;
    path = getPath(spec.suite);
    label = "" + screenshotName + " - " + screenshot.width + "x" + screenshot.height;
    filename = "" + (slug(spec.description + " " + screenshotName)) + "-" + screenshot.width + "x" + screenshot.height + ".png";
    return Q.fcall(function() {
      if (!spec.suite._screenshotsInitialized) {
        return Q.all([Q.nfcall(rimraf, path + '/missing'), Q.nfcall(rimraf, path + '/failed'), Q.nfcall(rimraf, path + '/diff')]);
      } else {
        return true;
      }
    }).then(function() {
      spec.suite._screenshotsInitialized = true;
      return Q.nfcall(fs.readFile, path + '/' + filename);
    }).then(function(data) {
      var deferred;
      if (screenshot.data === data.toString('base64')) {
        return {
          match: true
        };
      }
      deferred = Q.defer();
      resemble(new Buffer(screenshot.data, 'base64')).compareTo(data).onComplete(function(result) {
        if (result.misMatchPercentage === '0.00') {
          return deferred.resolve({
            match: true
          });
        } else {
          return deferred.resolve({
            match: false,
            label: label,
            path: path,
            filename: filename,
            actual: screenshot.data,
            difference: result.getImageDataUrl().substr(22),
            reason: "differed by " + result.misMatchPercentage + "%"
          });
        }
      });
      return deferred.promise;
    }, function(error) {
      if (error) {
        return Q({
          label: label,
          path: path,
          filename: filename,
          actual: screenshot.data,
          match: false,
          missing: true,
          reason: 'missing'
        });
      }
    }).then(function(result) {
      if (!result.match) {
        saveFailureImages(result);
      }
      return expect(result.match).toBe(true, "" + result.label + " on " + capabilityString + ": " + result.reason);
    });
  };

  saveFailureImages = function(result) {
    var writeImage;
    writeImage = function(path, data) {
      return Q.nfcall(mkdirp, path).then(function() {
        return Q.nfcall(fs.writeFile, "" + path + "/" + result.filename, data, {
          encoding: 'base64'
        });
      });
    };
    if (result.missing) {
      return Q.all([writeImage("" + result.path + "/missing", result.actual)]);
    } else {
      return Q.all([writeImage("" + result.path + "/failed", result.actual), writeImage("" + result.path + "/diff", result.difference)]);
    }
  };

  takeScreenshot = function(spec, screenshotName, delay) {
    var actualTakeScreenshot, screenSizes, setScreenSize, _ref;
    setScreenSize = function(width, height) {
      return browser.driver.manage().window().setSize(width, height);
    };
    screenSizes = (_ref = _.find(screenshotSizes, matchesCapabilities)) != null ? _ref.sizes : void 0;
    actualTakeScreenshot = function() {
      return browser.driver.manage().window().getSize().then(function(screenSize) {
        return browser.takeScreenshot().then(function(data) {
          return matchScreenshot(spec, screenshotName, {
            width: screenSize.width,
            height: screenSize.height,
            data: data
          });
        });
      });
    };
    if ((screenSizes != null ? screenSizes.length : void 0) > 0) {
      return screenSizes.reduce(function(soFar, size) {
        return soFar.then(setScreenSize(size.width, size.height).then(function() {
          return browser.sleep(delay);
        }).then(function() {
          return actualTakeScreenshot();
        }));
      }, Q(true));
    } else {
      return actualTakeScreenshot();
    }
  };


  /*
  Public API
   */

  exports.checkScreenshot = function(spec, screenshotName, delay) {
    if (disableScreenshots) {
      return;
    }
    delay = delay || 0;
    return takeScreenshot(spec, screenshotName, delay);
  };

}).call(this);
